export const CATEGORIAS = [
  {
    id: '1',
    nombre: 'Carnes',
    img_url: require('../assets/images/prod_lomo.png'),
  },
  {
    id: '2',
    nombre: 'Sandwiches',
    img_url: require('../assets/images/prod_sandwich.png'),
  },
  {
    id: '3',
    nombre: 'Pastas',
    img_url: require('../assets/images/prod_lomo.png'),
  },
  {
    id: '4',
    nombre: 'Guarniciones',
    img_url: require('../assets/images/prod_papasfritas.png'),
  },
  {
    id: '5',
    nombre: 'Bebidas',
    img_url: require('../assets/images/prod_coca.png'),
  },
];

export const PRODUCTOS = [
  {
    id: '1',
    nombre: 'Lomo vacuno a la parrilla',
    descripcion: 'Corte premium tierno y jugoso',
    estado: 'disponible',
    img_url: require('../assets/images/prod_lomo.png'),
    precio: 20000,
    stock: 10,
    categoria_id: '1',
  },
  {
    id: '2',
    nombre: 'Chorizo puro cerdo',
    descripcion: 'Chorizo artesanal de cerdo',
    estado: 'disponible',
    img_url: require('../assets/images/prod_chori.png'),
    precio: 5000,
    stock: 15,
    categoria_id: '1',
  },
  {
    id: '3',
    nombre: 'Ribs de cerdo a la barbacoa',
    descripcion: 'Costillas tiernas con salsa BBQ',
    estado: 'disponible',
    img_url: require('../assets/images/prod_asado.png'),
    precio: 18000,
    stock: 8,
    categoria_id: '1',
  },
  {
    id: '4',
    nombre: 'Pollo entero con papas fritas',
    descripcion: 'Pollo entero tierno con guarnición',
    estado: 'disponible',
    img_url: require('../assets/images/prod_asado.png'),
    precio: 12000,
    stock: 12,
    categoria_id: '1',
  },
  {
    id: '5',
    nombre: 'Sandwich de vacío',
    descripcion: 'Pan casero con chimichurri',
    estado: 'disponible',
    img_url: require('../assets/images/prod_sandwich.png'),
    precio: 8000,
    stock: 20,
    categoria_id: '2',
  },
  {
    id: '6',
    nombre: 'Papas fritas bastón',
    descripcion: 'Papas crocantes y doradas',
    estado: 'disponible',
    img_url: require('../assets/images/prod_papasfritas.png'),
    precio: 3000,
    stock: 30,
    categoria_id: '4',
  },
  {
    id: '7',
    nombre: 'Vacío al plato',
    descripcion: 'Al horno de barro tradicional',
    estado: 'disponible',
    img_url: require('../assets/images/prod_vacio.png'),
    precio: 16000,
    stock: 9,
    categoria_id: '1',
  },
  {
    id: '8',
    nombre: 'Tira de asado premium',
    descripcion: 'Tira jugosa a fuego lento',
    estado: 'disponible',
    img_url: require('../assets/images/prod_asado.png'),
    precio: 14000,
    stock: 11,
    categoria_id: '1',
  },
  {
    id: '10',
    nombre: 'Coca-Cola 1.5lt',
    descripcion: 'Bebida refrescante',
    estado: 'disponible',
    img_url: require('../assets/images/prod_coca.png'),
    precio: 2500,
    stock: 50,
    categoria_id: '5',
  },
  {
    id: '11',
    nombre: 'Coca-Cola Zero 1.5lt',
    descripcion: 'Bebida sin azúcar',
    estado: 'disponible',
    img_url: require('../assets/images/prod_cocazero.png'),
    precio: 2500,
    stock: 40,
    categoria_id: '5',
  },
  {
    id: '12',
    nombre: 'Sprite 1.5lt',
    descripcion: 'Bebida cítrica refrescante',
    estado: 'disponible',
    img_url: require('../assets/images/prod_sprite.png'),
    precio: 2500,
    stock: 35,
    categoria_id: '5',
  },
];