import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#C84B22', 
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 25,
    padding: 20,
    position: 'relative', 
    overflow: 'hidden', 
  },
  titleSection: {
    fontSize: 14,
    color: '#FAD3C3', 
    fontWeight: '600',
    marginBottom: 5,
  },
  contentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textContainer: {
    flex: 1,
    paddingRight: 10,
  },
  promoText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: 'white',
    lineHeight: 28,
  },
  highlightText: {
    color: '#FFE2B7', 
  },
  imageContainer: {
    width: 120,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  foodImage: {
    width: '100%',
    height: '100%',
  },
  arrowLeft: {
    position: 'absolute',
    left: -10,
    top: '55%',
    backgroundColor: 'white',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  arrowRight: {
    position: 'absolute',
    right: -10,
    top: '55%',
    backgroundColor: 'white',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    marginHorizontal: 3,
  },
  activeDot: {
    backgroundColor: '#FFE2B7', 
    width: 12, 
  },
});