import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';
import { FONTS } from '../../constants/fonts';

export const styles = StyleSheet.create({
  container: {
    marginTop: 25,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontFamily: FONTS.family.bold,
    fontSize: FONTS.bodyLarge,
    fontWeight: 'bold',
    color: COLORS.textMuted,
    letterSpacing: 0.5,
    marginBottom: 15,
    textTransform: 'uppercase',
  },
  card: {
    backgroundColor: COLORS.primary,
    borderRadius: 25,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  restaurantText: {
    fontFamily: FONTS.family.bold,
    fontSize: FONTS.bodyLarge,
    fontWeight: 'bold',
    color: COLORS.dropdownDark, // El verde oscuro de la paleta
    marginBottom: 6,
  },
  estimatedTimeText: {
    fontFamily: FONTS.family.bold,
    fontSize: FONTS.h4,
    fontWeight: 'bold',
    color: COLORS.backgroundLight,
    marginBottom: 15,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    marginHorizontal: -3, // Compensa el margen horizontal de los segmentos
  },
  segment: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 3,
  },
  activeSegment: {
    backgroundColor: '#0DF5E3', // Color cian vibrante de la imagen
  },
  inactiveSegment: {
    backgroundColor: '#FFFFFF', // Blanco puro
  },
  descriptionText: {
    fontFamily: FONTS.family.medium,
    fontSize: FONTS.small,
    fontWeight: '500',
    color: COLORS.backgroundLight,
    lineHeight: 18,
  },
  buttonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  reviewButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flex: 0.65,
  },
  reviewButtonText: {
    fontFamily: FONTS.family.bold,
    color: COLORS.primary,
    fontWeight: 'bold',
    fontSize: FONTS.body,
    marginLeft: 6,
  },
  dismissButton: {
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0.3,
  },
  dismissButtonText: {
    fontFamily: FONTS.family.semiBold,
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: FONTS.body,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    width: '92%',
    maxWidth: 400,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  modalTitle: {
    fontFamily: FONTS.family.bold,
    fontSize: FONTS.h4 || 20,
    fontWeight: 'bold',
    color: '#260C05',
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontFamily: FONTS.family.regular,
    fontSize: FONTS.body || 15,
    color: COLORS.textMuted || '#8E8E93',
    marginBottom: 20,
    textAlign: 'center',
  },
  starsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  starButton: {
    padding: 5,
    marginHorizontal: 4,
  },
  inputLabel: {
    fontFamily: FONTS.family.semiBold,
    fontSize: FONTS.body || 15,
    fontWeight: '600',
    color: '#260C05',
    marginBottom: 8,
  },
  textInput: {
    fontFamily: FONTS.family.regular,
    backgroundColor: '#F5F5F7',
    borderRadius: 15,
    padding: 15,
    height: 100,
    fontSize: FONTS.body || 15,
    color: '#260C05',
    textAlignVertical: 'top',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  modalButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalCancelButton: {
    flex: 0.47,
    backgroundColor: '#F5F5F7',
    borderRadius: 15,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelButtonText: {
    fontFamily: FONTS.family.bold,
    color: '#8E8E93',
    fontWeight: 'bold',
    fontSize: FONTS.body || 15,
  },
  modalSubmitButton: {
    flex: 0.47,
    backgroundColor: COLORS.primary,
    borderRadius: 15,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSubmitButtonText: {
    fontFamily: FONTS.family.bold,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: FONTS.body || 15,
  },
});
